### ISSUE TITLE
Vue 2?

### ISSUE THREAD

**Issue by ankush981** [scaccogatto/vue-geolocation#1]
Hello, thanks for the plugin! Has this been tested with Vue 2?

**Comment by scaccogatto** [comment]
It's tested ONLY with Vue2.

**Comment by ankush981** [comment]
Thanks! It'd be nice to mention this in the project sub-head. :smile:

**Comment by scaccogatto** [comment]
I think package,json deps are enough:

```"dependencies": {
    "vue": "^2.0.1"
  },```
