### ISSUE TITLE
accuracy not available

### ISSUE THREAD

**Issue by smelliott100** [scaccogatto/vue-geolocation#13]
The src implies you can use more than lat/lng, but they are not available in the object?

window.navigator.geolocation.getCurrentPosition(
          position => {
            resolve({
              lat: position.coords.latitude,
              lng: position.coords.longitude,
              altitude: position.coords.altitude,
              altitudeAccuracy: position.coords.altitudeAccuracy,
              accuracy: position.coords.accuracy
            })

**Comment by smelliott100** [comment]
I used the https://github.com/HCESrl/vue-geolocation.git fork and it works.

**Comment by smelliott100** [comment]
No, When I install Vue-geolocation (npm install --save vue-geolocation) the additional features you show in src (accuracy....) are not available in the object.  Looking @ your dist folder:

(function(o){t({lat:o.coords.latitude,lng:o.coords.longitude})

If i install HCEsrl's version:
npm install --save https://github.com/HCESrl/vue-geolocation.git

Then I have (accuracy....)  Looking @ his dst folder:

(function(o){e({lat:o.coords.latitude,lng:o.coords.longitude,altitude:o.coords.altitude,altitudeAccuracy:o.coords.altitudeAccuracy,accuracy:o.coords.accuracy})

**Comment by scaccogatto** [comment]
I will investigate

**Comment by gorbypark** [comment]
This is because the latest version on npm is 1.5.0 and altitude/accuracy were added in 1.6.0 and the current version is 1.7.0.  @scaccogatto can you push a new version to npm?

**Comment by scaccogatto** [comment]
Sorry for the inconvenience, the package is now live on npm, tagged as v.1.8.0
