### ISSUE TITLE
how to react to a declined location?

### ISSUE THREAD

**Issue by vesper8** [scaccogatto/vue-geolocation#2]
Hi there! Thanks for sharing this plugin.

I think

```
Vue.install(VueGeolocation);
```

Needs to be

```
Vue.use(VueGeolocation);
```

That's what worked for me

Otherwise I would like to know if there is currently, or if you could add, a way to easily react to a user declining to share their location (hitting block instead of accept)

**Comment by scaccogatto** [comment]
You can "catch" the Promise rejection:

```js
this.$getLocation()
  .catch(error=> {
    console.log(error);
  });
```

Anyway this README should be refined, you are right. You can do it by yourself or I will do it ASAP.

**Comment by sp00x** [comment]
Also, I guess it should be - naturally:

`import VueGeolocation from 'vue-browser-geolocation'; // -browser- part missing`  

.. :)
