### ISSUE TITLE
Watch user position

### ISSUE THREAD

**Issue by thanhthaohoang** [scaccogatto/vue-geolocation#5]
I'm using your vue-browser-geolocation in my Nuxtjs web app and it works well !

I would like to update user geolocation on my app in order to calculate distance between him and places coordinates. 

Do your plugin handles watchPosition() ?

**Comment by hkd987** [comment]
https://github.com/scaccogatto/vue-geolocation/pull/8

Currently an open pull request to make this happen.

**Comment by hkd987** [comment]
This issue can be closed.

**Comment by thanhthaohoang** [comment]
Hi !
In which hook do I have to write the watchPosition code ?
I want to follow the user position and update the marker on google maps.

**Comment by hkd987** [comment]
This should be inside its own method.
